name: Sync Toots from Mastodon

on:
  workflow_dispatch:
  schedule:
    - cron: "12 23 * * *"

#concurrency:
#  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Grab latest toots
        run: |
          ./.scripts/refreshtoots.py

      - name: Check if there's any changes
        id: verify_diff
        run: |
          if [ -n "$(git status --porcelain)" ]; then echo ::set-output name=changed::true; fi

      - name: Commit and push
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git add *.md
          git commit -m "New/Modified Toots"
          git push origin main
